import { promises as fs } from 'fs'
import path from 'path'
import matter from 'gray-matter'
import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

// Homepage Props
// ================================================
export async function getStaticProps() {
  const postsDirectory = path.join(process.cwd(), 'articles')
  const files = await fs.readdir(postsDirectory)

  const posts = files.map(async (filename) => {
    const filePath = path.join(postsDirectory, filename)
    const fileContents = await fs.readFile(filePath, 'utf-8')
    const slug = filename.replace('.md', '')

    const {data: frontMatter} = matter(fileContents)

    return {
      slug,
      frontMatter
    }
  })

  return {
    props: {
      posts: await Promise.all(posts),
    },
  }
}

// Homepage Component
// ================================================
export default function Home({ posts }) {

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>My Homepage with Blog Listings</h1>

      <ul>
        {posts.map((post, i) => (
            <li key={i}><Link href={'/posts/' + post.slug}><a>{post.frontMatter.title}</a></Link></li>
          )
        )}
      </ul>
    </div>
  )
}